[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_ENDPOINT = "https://portfolio-backend-fastapi-n184.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
